const $=(s)=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),events=window.SIGNAL_EVENTS;
const ui={time:$("#time"),score:$("#score"),combo:$("#combo"),alert:$("#alert-level"),energy:$("#energy"),reserve:$("#recharge"),overload:$("#overload"),cap:$("#grid-cap"),bar:$("#stability-bar"),stability:$("#stability-text"),message:$("#message"),effect:$("#effect-info"),tutorial:$("#tutorial"),overlay:$("#overlay"),start:$("#start-button"),mute:$("#mute-button"),selected:$("#selected-zone"),down:$("#power-down"),up:$("#power-up")};
const zones=[{name:"NORTH",label:"북부",key:"1",x:88,y:135,w:230,h:285,color:"#53bbff"},{name:"CENTRAL",label:"중앙",key:"2",x:365,y:135,w:230,h:285,color:"#bd8cff"},{name:"SOUTH",label:"남부",key:"3",x:642,y:135,w:230,h:285,color:"#ffb85c"}];
let state,animationId=0,audioContext;
function phase(t){return t<30000?{id:0,name:"학습",cap:1,gap:9500}:t<90000?{id:1,name:"압박",cap:2,gap:6200}:t<150000?{id:2,name:"연쇄 위기",cap:2,gap:4800}:{id:3,name:"대정전",cap:3,gap:3600};}
function audio(){if(!audioContext&&(window.AudioContext||window.webkitAudioContext))audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext?.state==="suspended")audioContext.resume().catch(()=>{});}
function tone(f,d,type="sine",delay=0){if(!audioContext||state.muted)return;const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,at);g.gain.setValueAtTime(.04,at);g.gain.exponentialRampToValueAtTime(.001,at+d);o.connect(g).connect(audioContext.destination);o.start(at);o.stop(at+d);}
function sound(k){if(k==="alert"){tone(600,.07,"square");tone(820,.1,"square",.1)}if(k==="ok"){tone(650,.06);tone(980,.12,"sine",.06)}if(k==="bad")tone(150,.2,"sawtooth");}
function pick(p,blocked=[]){const pool=events.filter(e=>e.minimumPhase<=Math.min(2,p.id)&&!blocked.includes(e.zone)),sum=pool.reduce((n,e)=>n+e.weight,0);let r=Math.random()*sum;return pool.find(e=>(r-=e.weight)<=0)||pool[0];}
function newGame(){cancelAnimationFrame(animationId);audio();const now=performance.now();state={running:true,start:now,last:now,score:0,combo:0,maxCombo:0,stability:100,active:[],next:1200,selected:0,allocation:[2,2,2],reserve:0,cap:6,overload:0,maxOverload:0,lastTransfer:0,transferUntil:0,bursts:[],flash:0,shake:0,firstMistake:true,abandoned:0,mini:null,special:null,specialDone:false,effect:"",mods:{fog:0,traffic:0,northHarm:0},muted:ui.mute.getAttribute("aria-pressed")==="true",reduced:matchMedia("(prefers-reduced-motion: reduce)").matches};ui.overlay.hidden=true;ui.tutorial.hidden=false;hud(180);animationId=requestAnimationFrame(loop);}
function spawn(t){const p=phase(t),blocked=state.active.map(a=>a.item.zone);if(state.active.length>=p.cap||blocked.length===3){state.next=t+900;return}const item=pick(p,blocked);state.active.push({item,zone:zones.find(z=>z.name===item.zone),progress:0,expires:t+item.duration*1000,ready:false});state.next=t+p.gap;state.message=`${item.title} 발생 · ${item.zone}에 ${item.energyCost}칸 필요`;sound("alert");}
function trimCap(){while(state.allocation.reduce((a,b)=>a+b,0)>state.cap){const i=state.allocation.indexOf(Math.max(...state.allocation));state.allocation[i]--;state.reserve++;}}
function select(i){if(!state?.running)return;state.selected=i;const ready=state.active.find(a=>a.ready&&a.zone===zones[i]);if(ready&&!state.mini)startMini(ready);else state.message=`${zones[i].name} 선택 · Q/E로 전력 이동`;hud(left());}
function transfer(d){if(!state?.running||state.mini)return;const i=state.selected,now=performance.now(),rapid=now-state.lastTransfer<900;if(d>0&&(state.reserve<1||state.allocation.reduce((a,b)=>a+b,0)>=state.cap)){state.message="예비 전력이 없습니다.";return}if(d<0&&!state.allocation[i]){state.message="회수할 전력이 없습니다.";return}state.allocation[i]+=d;state.reserve-=d;state.lastTransfer=now;state.transferUntil=now+380;state.overload=Math.min(100,state.overload+(rapid?10:5));state.maxOverload=Math.max(state.maxOverload,state.overload);state.message=`${zones[i].name} ${state.allocation[i]}칸 · 전환 중`;tone(d>0?520:330,.06,"square");hud(left());}
function startMini(a){const type=a.item.mini;state.mini={event:a,type,deadline:performance.now()-state.start+3500,nodes:type==="nodes"?[0,1,2].sort(()=>Math.random()-.5):null,index:0,needle:0};state.message=type==="nodes"?"복구 회로: 빛나는 노드를 순서대로 탭하세요.":"주파수 동기화: 중앙 녹색 구간에서 탭 또는 Space.";tone(780,.08);}
function miniInput(x,y){const m=state.mini;if(!m)return false;if(m.type==="frequency"){const success=Math.abs(m.needle-.5)<.14;finishMini(success);return true}const positions=[[420,480],[480,455],[540,480]];const hit=positions.findIndex(p=>Math.hypot(x-p[0],y-p[1])<28);if(hit===m.nodes[m.index]){m.index++;tone(650,.05);if(m.index===m.nodes.length)finishMini(true)}else finishMini(false);return true;}
function finishMini(ok){const m=state.mini,a=m.event;if(ok){const late=(performance.now()-state.start>a.expires-a.item.duration*1000*.25);resolve(a,late);}else{a.progress=.55;a.ready=false;state.combo=Math.max(0,state.combo-1);state.message="복구 동기화 실패 · 전력 배분을 유지해 다시 시도";sound("bad");}state.mini=null;}
function resolve(a,late){const i=state.active.indexOf(a),surplus=Math.max(0,state.allocation[zones.indexOf(a.zone)]-need(a)),traffic=state.mods.traffic>performance.now()-state.start?.75:1,metro=state.special?.id==="metro"&&a.item.zone==="CENTRAL"?1.5:1,multi=(1+state.overload*.0075+(late?.3:0))*traffic*metro,chain=state.active.filter(x=>x.ready).length>1?.25:0,gain=Math.round(a.item.rescued*(multi+chain));state.score+=gain;state.combo++;state.maxCombo=Math.max(state.maxCombo,state.combo);state.stability=Math.min(100,state.stability+a.item.stabilityEffect);state.message=`${a.item.title} 복구 · +${gain}${late?" 위험 보너스":""}`;state.active.splice(i,1);state.overload=Math.min(100,state.overload+surplus*5);state.maxOverload=Math.max(state.maxOverload,state.overload);state.bursts.push({text:chain?"CHAIN +25%":`+${gain} RESCUED`,color:"#83ffe0",life:1});sound("ok");}
function fail(a){let dmg=a.item.failureEffect+state.mods.northHarm,t=performance.now()-state.start;state.abandoned++;state.combo=Math.max(0,state.combo-2);if(a.item.effect==="comms"){state.mods.fog=t+18000;state.effect="통신 장애: 사건 정보가 가려집니다";}if(a.item.effect==="traffic"){state.mods.traffic=t+22000;state.effect="교통 마비: 구조 보상이 감소합니다";}if(a.item.effect==="capacity"){state.cap=Math.max(3,state.cap-1);trimCap();state.effect="발전소 손상: 전력망 용량 -1";}if(a.item.effect==="northDamage"){state.mods.northHarm+=2;state.effect="병원 정전: 다음 피해량 +2";}const gentle=state.firstMistake;state.firstMistake=false;dmg=gentle?Math.ceil(dmg*.45):dmg;state.stability=Math.max(0,state.stability-dmg);state.message=`${a.item.title} 포기 · 안정도 -${dmg}${gentle?" (첫 피해 완화)":""}`;state.flash=13;state.shake=state.reduced?0:12;state.active.splice(state.active.indexOf(a),1);sound("bad");}
function special(t){if(state.specialDone||t<105000)return;state.specialDone=true;const all=[{id:"heat",text:"폭염: 18초간 NORTH 필요 전력 +1",until:t+18000},{id:"cyber",text:"사이버 공격: 12초간 사건 정보 왜곡",until:t+12000},{id:"fire",text:"발전소 화재: SOUTH 2칸을 15초 유지",until:t+15000},{id:"metro",text:"지하철 고립: CENTRAL 구조 보상 +50%",until:t+16000}];state.special=all[Math.floor(Math.random()*all.length)];state.effect=`특별 위기 · ${state.special.text}`;state.message=state.effect;state.bursts.push({text:"SPECIAL CRISIS",color:"#ffcf6e",life:1});sound("alert");}
function updateSpecial(t){if(!state.special)return;if(state.special.id==="fire"&&state.allocation[2]<2){state.cap=Math.max(3,state.cap-1);trimCap();state.effect="발전소 화재 악화: 전력망 용량 -1";state.special=null;return}if(t>=state.special.until){state.special=null;state.effect="특별 위기 종료";}}
function hud(left){const m=Math.floor(left/60).toString().padStart(2,"0"),s=Math.ceil(left%60).toString().padStart(2,"0");ui.time.textContent=`${m}:${s}`;ui.score.textContent=state.score;ui.combo.textContent=`x${state.combo}`;ui.alert.textContent=phase(performance.now()-state.start).name;ui.energy.textContent=`${state.allocation.reduce((a,b)=>a+b,0)} / ${state.cap}`;ui.reserve.textContent=state.reserve;ui.overload.textContent=`${Math.round(state.overload)}%`;ui.cap.textContent=state.cap;ui.bar.style.width=`${state.stability}%`;ui.stability.textContent=`${state.stability}%`;ui.selected.textContent=zones[state.selected].name;ui.message.textContent=state.message;ui.effect.textContent=state.effect||"";}
function left(){return Math.max(0,180-(performance.now()-state.start)/1000);}
function tutorial(t){if(t>15000){ui.tutorial.hidden=true;return}ui.tutorial.hidden=false;ui.tutorial.textContent=t<5000?"전력이 필요한 구역을 선택하고 Q/E로 6칸을 재배분하세요.":t<10000?"전력이 충분하면 사건의 복구 게이지가 찹니다. 완료된 사건을 선택해 짧게 복구하세요.":"한 구역만 살릴 수 없을 때가 옵니다. 과부하는 점수, 과하면 전체 정전입니다.";}
function draw(t){const{width:w,height:h}=canvas,dx=state.shake&&!state.reduced?(Math.random()-.5)*state.shake:0;ctx.save();ctx.translate(dx,0);ctx.fillStyle="#081525";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#183556";for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
zones.forEach((z,i)=>{const a=state.active.find(x=>x.zone===z),sel=i===state.selected,p=state.allocation[i],hidden=state.mods.fog>t;ctx.fillStyle=a?"#3b1b32":"#102943";ctx.fillRect(z.x,z.y,z.w,z.h);ctx.strokeStyle=sel?"#6df2cd":a?"#ff7180":z.color;ctx.lineWidth=sel?5:2;ctx.strokeRect(z.x,z.y,z.w,z.h);ctx.textAlign="center";ctx.fillStyle="#dfeeff";ctx.font="800 21px system-ui";ctx.fillText(z.name,z.x+115,z.y+38);for(let n=0;n<6;n++){ctx.fillStyle=n<p?z.color:"#1c3550";ctx.fillRect(z.x+28+n*29,z.y+64,21,19);}ctx.fillStyle="#dfeeff";ctx.font="800 21px system-ui";ctx.fillText(`${p} POWER`,z.x+115,z.y+118);if(a){ctx.fillStyle=a.ready?"#6df2cd":"#fff";ctx.font="800 18px system-ui";ctx.fillText(a.ready?"READY: SELECT TO REPAIR":hidden?"?? SIGNAL ??":`${a.item.icon} ${a.item.title}`,z.x+115,z.y+160);ctx.font="700 13px system-ui";ctx.fillStyle="#b8c8d9";ctx.fillText(hidden?"정보 교란 중":`필요 ${need(a)} · ${a.item.description}`,z.x+115,z.y+187);ctx.fillStyle="#0008";ctx.fillRect(z.x+20,z.y+210,z.w-40,7);ctx.fillStyle="#ff7180";ctx.fillRect(z.x+20,z.y+210,(z.w-40)*Math.max(0,(a.expires-t)/(a.item.duration*1000)),7);ctx.fillStyle="#6df2cd";ctx.fillRect(z.x+20,z.y+226,(z.w-40)*a.progress,6);}ctx.font="700 13px system-ui";ctx.fillStyle="#9eb7d0";ctx.fillText(`[${z.key}] Q − / E +`,z.x+115,z.y+264);});
if(state.mini){const m=state.mini;ctx.fillStyle="#06111ef2";ctx.fillRect(350,435,260,95);ctx.strokeStyle="#6df2cd";ctx.strokeRect(350,435,260,95);ctx.textAlign="center";ctx.fillStyle="#eafff9";ctx.font="800 14px system-ui";ctx.fillText(m.type==="nodes"?"REPAIR NODES: 빛나는 순서 탭":"SYNC FREQUENCY: 녹색 중앙에서 탭 / SPACE",480,452);if(m.type==="nodes"){[[420,480],[480,455],[540,480]].forEach((p,i)=>{ctx.fillStyle=i===m.nodes[m.index]?"#6df2cd":"#264763";ctx.beginPath();ctx.arc(...p,20,0,Math.PI*2);ctx.fill();});}else{ctx.fillStyle="#27465f";ctx.fillRect(375,480,210,10);ctx.fillStyle="#6df2cd";ctx.fillRect(451,480,58,10);ctx.fillStyle="#ffcf6e";ctx.fillRect(375+m.needle*210,468,5,34);}}
state.bursts.forEach(b=>{ctx.globalAlpha=b.life;ctx.textAlign="center";ctx.fillStyle=b.color;ctx.font="900 27px system-ui";ctx.fillText(b.text,w/2,80+(1-b.life)*-40);b.life-=.022});state.bursts=state.bursts.filter(b=>b.life>0);ctx.globalAlpha=1;if(state.flash){ctx.fillStyle="rgba(255,55,78,.12)";ctx.fillRect(0,0,w,h);state.flash--;}if(state.shake)state.shake--;ctx.restore();}
function need(a){return a.item.energyCost+(state.special?.id==="heat"&&a.item.zone==="NORTH"?1:0);}
function end(reason="SHIFT COMPLETE"){if(!state?.running)return;state.running=false;cancelAnimationFrame(animationId);ui.tutorial.hidden=true;let style=state.maxOverload>75?"위험한 승부사":state.abandoned<3?"안정적인 관리자":state.allocation[0]>=3?"시민 우선 구조자":"인프라 우선 전략가";let ending=state.stability>60?"도시는 새벽을 맞았습니다.":state.stability>25?"도시는 상처 입었지만 버텼습니다.":"도시는 긴 밤을 기억합니다.";let high=0;try{high=Math.max(+localStorage.getItem("signal-keeper-high")||0,state.score);localStorage.setItem("signal-keeper-high",high)}catch{}ui.overlay.innerHTML=`<p class="eyebrow">${reason}</p><h2>${ending}</h2><p>구조 시민 <b>${state.score}</b> · 안정도 <b>${state.stability}%</b> · 최대 콤보 <b>${state.maxCombo}</b><br>포기 사건 <b>${state.abandoned}</b> · 최대 과부하 <b>${Math.round(state.maxOverload)}%</b><br><b>${style}</b> · 최고 점수 <b>${high}</b></p><button id="start-button" type="button">다시 근무하기 <span>↵</span></button>`;ui.overlay.hidden=false;$("#start-button").addEventListener("click",newGame,{once:true});}
function loop(now){if(!state?.running)return;const t=now-state.start,l=Math.max(0,180-t/1000),dt=Math.min(.1,(now-state.last)/1000);state.last=now;if(l<=0){end();return}state.overload=Math.max(0,state.overload-dt*3.1);if(state.overload>=100){end("GRID OVERLOAD");return}special(t);updateSpecial(t);if(t>=state.next)spawn(t);state.active.slice().forEach(a=>{if(a.ready)return;if(t>=a.expires){fail(a);return}const supply=state.allocation[zones.indexOf(a.zone)],extra=Math.max(0,supply-need(a)),rate=supply>=need(a)?(1+extra*.55)/(a.item.duration*.76):.08/a.item.duration;a.progress+=rate*dt*(now<state.transferUntil?.35:1);if(extra)state.overload=Math.min(100,state.overload+extra*dt*1.25);if(a.progress>=1){a.progress=1;a.ready=true;state.message=`${a.item.title} 준비 완료 · 해당 구역을 선택해 복구`;tone(850,.08);}});if(state.mini){state.mini.needle=(state.mini.needle+dt*.9)%1;if(t>=state.mini.deadline)finishMini(false)}if(state.stability<=0){end("CITY BLACKOUT");return}tutorial(t);hud(l);draw(t);animationId=requestAnimationFrame(loop);}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
canvas.addEventListener("pointerdown",e=>{const p=point(e);if(miniInput(p.x,p.y))return;const i=zones.findIndex(z=>p.x>=z.x&&p.x<=z.x+z.w&&p.y>=z.y&&p.y<=z.y+z.h);if(i>=0)select(i);});ui.start.addEventListener("click",newGame);ui.down.addEventListener("click",()=>transfer(-1));ui.up.addEventListener("click",()=>transfer(1));window.addEventListener("keydown",e=>{if(e.key==="Enter"&&!state?.running)$("#start-button")?.click();const i=zones.findIndex(z=>z.key===e.key);if(i>=0)select(i);if(e.key.toLowerCase()==="q")transfer(-1);if(e.key.toLowerCase()==="e")transfer(1);if((e.code==="Space"||e.key===" ")&&state?.mini)miniInput(0,0);});ui.mute.addEventListener("click",()=>{const m=ui.mute.getAttribute("aria-pressed")!=="true";ui.mute.setAttribute("aria-pressed",m);ui.mute.textContent=m?"🔇":"🔊";if(state)state.muted=m});ctx.fillStyle="#081525";ctx.fillRect(0,0,canvas.width,canvas.height);
