(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.EquipmentData = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const slots = Object.freeze(["weapon", "armor", "relic"]);
  const rarities = Object.freeze(["common", "rare", "legendary"]);
  const rarityWeights = Object.freeze({ common: 65, rare: 28, legendary: 7 });
  const rewards = Object.freeze({
    candidateCount: 3,
    normalRoomChance: 0.35,
    eliteRoomChance: 0.75,
    anchorRoomChance: 1,
  });
  const limits = Object.freeze({
    minFireInterval: 0.12,
    maxDashCharges: 2,
    maxEchoDamageMultiplier: 1.2,
    minOverloadCooldown: 0.7,
    minMaxHp: 45,
    maxShardRadius: 220,
    maxMemorySeconds: 3,
  });
  const upgradeRules = Object.freeze({
    splitShot: Object.freeze({ projectileCount: 2, spreadDegrees: 10, damageMultiplier: 0.7 }),
    pulseCannon: Object.freeze({
      damageMultiplier: 1.55,
      fireIntervalMultiplier: 1.62,
      projectileSpeed: 650,
      pierce: 3,
      size: 6,
    }),
    vectorStackRechargeMultiplier: 0.9,
    vectorDashDistanceMultiplier: 0.88,
    extendedMemoryStackBonus: 1,
  });

  const items = [
    {
      id: "phase-carbine",
      name: "PHASE CARBINE",
      slot: "weapon",
      rarity: "common",
      description: "현재 기본 자동 사격과 동일한 안정형 중거리 카빈.",
      statSummary: ["중거리", "표준 연사", "표준 피해"],
      advantages: ["안정적인 모든 거리 대응"],
      drawbacks: ["특화 효과 없음"],
      modifiers: { fireIntervalMultiplier: 1, damageMultiplier: 1 },
      fireProfile: {
        type: "carbine",
        projectileCount: 1,
        spreadDegrees: 0,
        speedMultiplier: 1,
        rangeMultiplier: 1,
        pierce: 0,
        coreDamageMultiplier: 1,
      },
      echoRules: {},
      visual: { color: "#fff1d7", icon: "▰", profile: "carbine" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "breach-shotgun",
      name: "BREACH SHOTGUN",
      slot: "weapon",
      rarity: "rare",
      description: "근거리 부채꼴 탄막으로 몬스터 무리를 돌파한다.",
      statSummary: ["5발 · 32°", "연사 간격 ×1.55", "사거리 ×0.55"],
      advantages: ["근거리 다중 대상", "넓은 사격선"],
      drawbacks: ["짧은 사거리", "느린 연사"],
      modifiers: { fireIntervalMultiplier: 1.55, damageMultiplier: 0.34 },
      fireProfile: {
        type: "shotgun",
        projectileCount: 5,
        spreadDegrees: 32,
        speedMultiplier: 0.9,
        rangeMultiplier: 0.55,
        pierce: 0,
        coreDamageMultiplier: 0.82,
      },
      echoRules: {},
      visual: { color: "#ffbc72", icon: "▱", profile: "shotgun" },
      incompatible: [],
      incompatibleUpgrades: ["split-shot", "charge-lance"],
    },
    {
      id: "pulse-rifle",
      name: "PULSE RIFLE",
      slot: "weapon",
      rarity: "rare",
      description: "빠른 관통탄으로 일렬의 적과 릴레이를 꿰뚫는다.",
      statSummary: ["관통 2", "피해 ×1.35", "연사 간격 ×1.45"],
      advantages: ["적·릴레이 관통", "긴 유효 거리"],
      drawbacks: ["느린 연사", "벽 관통 불가"],
      modifiers: { fireIntervalMultiplier: 1.45, damageMultiplier: 1.35 },
      fireProfile: {
        type: "rifle",
        projectileCount: 1,
        spreadDegrees: 0,
        speedMultiplier: 1.25,
        rangeMultiplier: 1.2,
        pierce: 2,
        coreDamageMultiplier: 1,
      },
      echoRules: {},
      visual: { color: "#72dfff", icon: "━", profile: "rifle" },
      incompatible: [],
      incompatibleUpgrades: ["pulse-cannon"],
    },
    {
      id: "chrono-vest",
      name: "CHRONO VEST",
      slot: "armor",
      rarity: "common",
      description: "각 루프 시작 시 피해를 먼저 흡수하는 시간 보호막을 생성한다.",
      statSummary: ["루프 보호막 25", "방 이동 시 재충전 없음"],
      advantages: ["반복 루프 안정성"],
      drawbacks: ["보호막 소진 후 추가 방어 없음"],
      modifiers: { loopShield: 25 },
      fireProfile: {},
      echoRules: {},
      visual: { color: "#72cfff", icon: "⬡", profile: "vest" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "vector-harness",
      name: "VECTOR HARNESS",
      slot: "armor",
      rarity: "rare",
      description: "짧은 대시 두 번을 저장해 위험 구간을 연속 돌파한다.",
      statSummary: ["대시 충전 2", "대시 거리 -12%"],
      advantages: ["연속 회피와 위치 선점"],
      drawbacks: ["개별 대시 거리 감소"],
      modifiers: { dashCharges: 2, dashDistanceMultiplier: 0.88 },
      fireProfile: {},
      echoRules: {},
      visual: { color: "#72fff0", icon: "»", profile: "harness" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "hunter-coat",
      name: "HUNTER COAT",
      slot: "armor",
      rarity: "legendary",
      description: "생존력을 희생해 기동성과 Chrono Shard 수집력을 높인다.",
      statSummary: ["이동 +10%", "Shard 반경 +45%", "최대 체력 -12%"],
      advantages: ["빠른 자원 회수"],
      drawbacks: ["낮은 최대 체력"],
      modifiers: { moveSpeedMultiplier: 1.1, shardRadiusMultiplier: 1.45, maxHpMultiplier: 0.88 },
      fireProfile: {},
      echoRules: {},
      visual: { color: "#c48bff", icon: "⌄", profile: "coat" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "echo-lens",
      name: "ECHO LENS",
      slot: "relic",
      rarity: "rare",
      description: "현재 화력을 낮추고 과거 시간선의 사격을 증폭한다.",
      statSummary: ["Echo 피해 +25%", "현재 피해 -8%"],
      advantages: ["계획된 Echo 협공 강화"],
      drawbacks: ["현재 플레이어 화력 감소"],
      modifiers: { playerDamageMultiplier: 0.92, echoDamageMultiplier: 1.25 },
      fireProfile: {},
      echoRules: { damageMultiplier: 1.25 },
      visual: { color: "#54fff4", icon: "◉", profile: "lens" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "memory-core",
      name: "MEMORY CORE",
      slot: "relic",
      rarity: "legendary",
      description: "기록 종료 후 Echo가 마지막 위치에서 지원 사격을 지속한다.",
      statSummary: ["Echo 유지 +2초", "중복 상한 3초"],
      advantages: ["고정 사격선 연장"],
      drawbacks: ["연장 중 이동 불가"],
      modifiers: { memorySeconds: 2 },
      fireProfile: {},
      echoRules: { memorySeconds: 2 },
      visual: { color: "#7ef5ff", icon: "◌", profile: "memory" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
    {
      id: "paradox-ring",
      name: "PARADOX RING",
      slot: "relic",
      rarity: "legendary",
      description: "정확한 동시 타격의 폭발력을 높이고 재동기화를 앞당긴다.",
      statSummary: ["Overload 피해 +35%", "내부 쿨다운 -15%"],
      advantages: ["Echo 동시 타격 보상"],
      drawbacks: ["단독 사격에는 효과 없음"],
      modifiers: { overloadDamageMultiplier: 1.35, overloadCooldownMultiplier: 0.85 },
      fireProfile: {},
      echoRules: {},
      visual: { color: "#ff8cf1", icon: "◎", profile: "paradox" },
      incompatible: [],
      incompatibleUpgrades: [],
    },
  ];

  const frozenItems = Object.freeze(
    items.map((item) =>
      Object.freeze({
        ...item,
        statSummary: Object.freeze(item.statSummary.slice()),
        advantages: Object.freeze(item.advantages.slice()),
        drawbacks: Object.freeze(item.drawbacks.slice()),
        modifiers: Object.freeze({ ...item.modifiers }),
        fireProfile: Object.freeze({ ...item.fireProfile }),
        echoRules: Object.freeze({ ...item.echoRules }),
        visual: Object.freeze({ ...item.visual }),
        incompatible: Object.freeze(item.incompatible.slice()),
        incompatibleUpgrades: Object.freeze(item.incompatibleUpgrades.slice()),
      })
    )
  );

  return Object.freeze({
    items: frozenItems,
    slots,
    rarities,
    rarityWeights,
    rewards,
    limits,
    upgradeRules,
  });
});
