(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.MonsterData = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  function selectGuardTarget(relays, core, enemy) {
    if (!relays.length) return core;
    return relays.reduce((nearest, relay) => {
      const current = (enemy.x - relay.x) ** 2 + (enemy.y - relay.y) ** 2;
      const best = (enemy.x - nearest.x) ** 2 + (enemy.y - nearest.y) ** 2;
      return current < best ? relay : nearest;
    }, relays[0]);
  }

  return Object.freeze({
    selectGuardTarget,
    chaser: Object.freeze({
      id: "chaser",
      name: "RIFT HOUND",
      role: "pursuer",
      radius: 15,
      hp: 30,
      speed: 92,
      score: 120,
      color: "#f03b56",
      accent: "#ff9a7d",
      behavior: "pursue",
      reward: 8,
      visual: "hound",
    }),
    shooter: Object.freeze({
      id: "shooter",
      name: "SPORE CASTER",
      role: "artillery",
      radius: 18,
      hp: 46,
      speed: 62,
      score: 180,
      color: "#ba2949",
      accent: "#ffd0df",
      behavior: "shoot",
      reward: 10,
      visual: "caster",
    }),
    blocker: Object.freeze({
      id: "blocker",
      name: "ANCHOR BRUTE",
      role: "interceptor",
      radius: 23,
      hp: 95,
      speed: 48,
      score: 240,
      color: "#871d3b",
      accent: "#ff6685",
      behavior: "guard-relay",
      reward: 18,
      visual: "brute",
    }),
    leech: Object.freeze({
      id: "leech",
      name: "CHRONO LEECH",
      role: "debuffer",
      radius: 13,
      hp: 24,
      speed: 78,
      score: 150,
      color: "#a53c83",
      accent: "#ff8ee1",
      behavior: "leech",
      reward: 10,
      visual: "leech",
    }),
    "core-guard": Object.freeze({
      id: "core-guard",
      name: "CORE GUARD",
      role: "anchor-support",
      radius: 21,
      hp: 82,
      speed: 42,
      score: 260,
      color: "#6943ad",
      accent: "#c8a1ff",
      behavior: "guard-core",
      reward: 22,
      visual: "guard",
    }),
    exploder: Object.freeze({
      id: "exploder",
      name: "RIFT BLOATER",
      role: "chain-reaction",
      radius: 17,
      hp: 38,
      speed: 55,
      score: 210,
      color: "#cf542f",
      accent: "#ffd06d",
      behavior: "explode",
      reward: 15,
      visual: "bloater",
    }),
    "corrupted-echo": Object.freeze({
      id: "corrupted-echo",
      name: "오염된 ECHO-07",
      role: "record-replay",
      radius: 19,
      hp: 72,
      speed: 0,
      score: 320,
      color: "#7d263f",
      accent: "#5de0d3",
      behavior: "corrupted-replay",
      reward: 24,
      visual: "corrupted",
      elite: true,
    }),
    "rift-warden": Object.freeze({
      id: "rift-warden",
      name: "RIFT WARDEN",
      role: "echo-gatekeeper",
      radius: 31,
      hp: 280,
      speed: 38,
      score: 700,
      color: "#75506f",
      accent: "#73c9bf",
      behavior: "boss",
      reward: 40,
      visual: "guard",
      boss: true,
      elite: true,
    }),
    "chrono-abomination": Object.freeze({
      id: "chrono-abomination",
      name: "CHRONO ABOMINATION",
      role: "stage-guardian",
      radius: 40,
      hp: 520,
      speed: 30,
      score: 1400,
      color: "#852f43",
      accent: "#e2c49c",
      behavior: "boss",
      reward: 70,
      visual: "brute",
      boss: true,
      elite: true,
    }),
  });
});
